secretGenerator:
  - name: db-password
    literals:
      - password=supersecuredpasswordhere
  - name: django
    literals:
      - secret=secretkey123
resources:
  - postgres.yaml
  - django.yaml
  